import fs from 'fs';
import chalk from 'chalk';
import CLILog from '../../lib/CLILog.js';
import writeDeploymentTokenToDisk from './writeDeploymentTokenToDisk.js';
import isValidJSONString from '../../lib/isValidJSONString.js';

export default async (args = {}, options = {}) => {
  const hasJoystickFolder = fs.existsSync('.joystick');

  if (!hasJoystickFolder) {
    CLILog('This is not a Joystick project. A .joystick folder could not be found.', {
      level: 'danger',
      docs: 'https://github.com/cheatcode/joystick',
    });

    process.exit(0);
  }

  const hasDeploymentTokenFile = fs.existsSync('.deploy/token.json');

  if (!hasDeploymentTokenFile && !options.token) {
    CLILog(`In order to deploy, ${chalk.yellowBright('a deployment token must be passed via the -t or --token flag when running joystick deploy, or, via the .deploy/token.json file at the root of your project')} (automatically generated as part of a previous deployment).`, {
      level: 'danger',
      docs: 'https://cheatcode.co/docs/deploy/deployment-tokens',
    });

    process.exit(0);
  }

  if (options.token) {
    writeDeploymentTokenToDisk(options.token);
  }

  const deploymentTokenFile = hasDeploymentTokenFile ? isValidJSONString(fs.readFileSync('.deploy/token.json')) : null;
  const deploymentToken = deploymentTokenFile?.deploymentToken || options.token;

  console.log({ deploymentTokenFile, deploymentToken });
};


// import loginToCheatCode from './lib/loginToCheatCode.js';
// import prompts from './lib/prompts.js';
// import getDeployment from './lib/getDeployment.js';

// // TODO: If no existing token file or user login, prompt and ask: "How do you want to login? [Token, Email/Password]"
// // When someone uses a token, record their mac address. If they reach a limit of machines, they can upgrade.
// // 
// // Deployment tokens will be generated by the subscription owner on their account. They can generate up to the alotted number and label each one. Also give an option to email the token to a developer.
// // Deploy Startup ($29/mo) = Up to 5 Users // Deploy Small Business ($39/mo) = Up to 10 // Deploy Enterprise ($199/mo) = Unlimited Users  // Deploy Forever?

// const login = await inquirer.prompt(prompts.login()).then((answers) => answers);
// const account = await loginToCheatCode(login?.emailAddress, login?.password);

// if (!account) {
//   console.log('\n');
//   process.exit(0);
// }

// const domain = await inquirer.prompt(prompts.domain()).then((answers) => answers?.domain);
// const deployment = await getDeployment(domain, account?.cookies);

// if (deployment?.status === 'undeployed') {
//   const deploymentToExecute = await inquirer.prompt(prompts.initialDeployment(account?.user));
//   console.log(deploymentToExecute);

//   // NOTE: Initial deployment involves: creating servers, uploading/unpacking code, installing dependencies, and setting up the config scripts.
//   // After install, prompt user to run joystick deployment <domain> ssl or visit the dashboard to generate
//   // their SSL certs (this talks to the load balancers, runs certbot, and then shares the cert between each load balancer)

//   // TODO: Initial provisioning takes ~2 minutes for most deployments. After that's complete,
//   // you will be prompted to update your DNS records and provision your SSL certificate.

//   // TODO: When the provisioning step is finished, have a big warning that says
//   /*
//     In order to complete deployment, please add the following DNS records to your domain and the run joystick deployment cheatcode.co ssl
//     to provision your SSL certificates.

//     Type  Domain Name   IP Address    TTL
//     -------------------------------------------------------------------------
//     A     cheatcode.co  192.168.1.1   Lowest Possible Value
//     A     cheatcode.co  192.168.1.2   Lowest Possible Value

//   */
// }