export default [
  // NOTE: Internal methods passed automatically via Joystick.
  "_componentId",
  "_ssrId",
  "api",
  "dataFromSSR",
  "existingProps",
  "existingState",
  "instanceId",
  "parent",
  "req",
  // NOTE: User-defined or standard methods.
  "css",
  "data",
  "defaultProps",
  "events",
  "id",
  "lifecycle",
  "methods",
  "name",
  "props",
  "render",
  "state",
  "translations",
  "url",
  "websockets",
  "wrapper",
];
